//
//  Taplytics.h
//  Taplytics
//
//  Copyright (c) 2013 Syrp Inc. All rights reserved.
//

#import "TaplyticsManager.h"

// UIElements
#import "TLButton.h"
#import "UIButton+TLButton.h"
#import "TLImageView.h"
#import "UIImageView+TLImageView.h"
#import "TLLabel.h"
#import "UILabel+TLLabel.h"
#import "TLView.h"
#import "UIView+TLView.h"
#import "TLTextField.h"
#import "UITextField+TLTextField.h"
#import "TLScrollView.h"
#import "TLTableViewCell.h"
#import "UITableViewCell+TLTableViewCell.h"
#import "TLBarButtonItem.h"
#import "UIBarButtonItem+TLBarButtonItem.h"
#import "TLSwitch.h"
#import "UISwitch+TLSwitch.h"
#import "TLCollectionViewFlowLayout.h"
#import "UICollectionViewFlowLayout+TLCollectionViewFlowLayout.h"
#import "TLCollectionViewCell.h"
#import "UICollectionViewCell+TLCollectionViewCell.h"
#import "TLCollectionReusableView.h"
#import "UICollectionReusableView+TLCollectionReusableView.h"
#import "TLTableView.h"
#import "UITableView+TLTableView.h"
#import "UIViewController+TLViewController.h"
#import "TLWebView.h"
#import "UIWebView+TLWebView.h"
#import "TLAlertView.h"
#import "UIAlertView+TLAlertView.h"
#import "TLActionSheet.h"
#import "UIActionSheet+TLActionSheet.h"
#import "TLSlider.h"
#import "UISlider+TLSlider.h"
#import "TLStepper.h"
#import "UIStepper+TLStepper.h"
#import "TLSegmentedControl.h"
#import "UISegmentedControl+TLSegmentedControl.h"
#import "TLPickerView.h"
#import "UIPickerView+TLPickerView.h"
#import "TLDatePicker.h"
#import "UIDatePicker+TLDatePicker.h"
#import "TLPageControl.h"
#import "UIPageControl+TLPageControl.h"
#import "TLProgressView.h"
#import "UIProgressView+TLProgressView.h"
#import "TLSearchBar.h"
#import "UISearchBar+TLSearchBar.h"
#import "TLActivityIndicatorView.h"
#import "UIActivityIndicatorView+TLActivityIndicatorView.h"
